# modules/PulsR/SportabzeichenBundle/Resources/config/services.yml
services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    PulsR\SportabzeichenBundle\Controller\:
        resource: '../../Controller/*'
        public: true
        tags: ['controller.service_arguments']

    PulsR\SportabzeichenBundle\EventListener\:
        resource: '../../EventListener/*'

    PulsR\SportabzeichenBundle\Crud\:
        resource: '../../Crud/*'
        arguments:
          $objectManager: '@IServ\CrudBundle\Doctrine\ORM\ORMObjectManager'
        public: true
        tags: ['iserv.crud']
