doctrine:
  dbal:
    url: 'pgsql://postgres:postgres@localhost:5432/sportabzeichen'
  orm:
    auto_generate_proxy_classes: true
    mappings:
      SportabzeichenBundle:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/PulsR/SportabzeichenBundle/Entity'
        prefix: 'PulsR\SportabzeichenBundle\Entity'
        alias: SportabzeichenBundle
